### ISSUE TITLE
Add `core=minetest` so that `core` also gives autocomplete etc

### ISSUE THREAD

**Issue by SumianVoice** [GreenXenith/luanti-tools#47] opened 2024-11-04 21:27 UTC
Currently `core` is not covered by the extension, but now that it's a preferred namespace to `minetest`, it would be nice to have autocomplete etc for it.

**Comment by mark-wiemer** [comment] 2024-12-14 11:04
Dupe of #12

**Closed** 2024-12-14 20:17 UTC
